# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_resource_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='constraints',
            field=models.ManyToManyField(blank=True, related_name='resources', to='constraint.Constraint'),
        ),
    ]
