# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='fullfield',
            field=models.ManyToManyField(blank=True, related_name='constraints', to=settings.AUTH_USER_MODEL),
        ),
    ]
