# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20171030_1342'),
        ('constraint', '0002_auto_20171102_2307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='constraint',
            unique_together=set([('name', 'group')]),
        ),
    ]
